
# Automatically generated by /Users/mshafae/github/cpsc120/cpsc-120-solution-lab-07/.action/ccsrcutilities.py on 2023-10-16 19:08:21

TOPTARGETS = all clean spotless format lint header test unittest

SUBDIRS = $(wildcard part-?/.)

default all: all

$(TOPTARGETS): $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -f Makefile -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)

